[dependencies]

[script-dependencies]
glob = { git = "https://github.com/Zxilly/glob-cj.git", tag = "v0.1.0" }

[ffi.c]
clang = { path = "D:/Tool/mingw64/bin" }

[package]
  cjc-version = "0.58.3"
  compile-option = ""
  description = "A simple C binding generator for Cangjie"
  link-option = "-lclang"
  name = "cjbind"
  output-type = "executable"
  override-compile-option = ""
  src-dir = ""
  target-dir = ""
  version = "1.0.0"
  package-configuration = {}
