name: Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  release:
    types: ["created"]

permissions:
  contents: "write"

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            sys: linux
            arch: x64
            ext: ""
            friendly_name: "Linux (x64)"
          - os: ubuntu-24.04-arm
            sys: linux
            arch: arm64
            ext: ""
            friendly_name: "Linux (ARM64)"
          - os: macos-15
            sys: darwin
            arch: arm64
            ext: ""
            friendly_name: "macOS (Apple Silicon)"
          - os: windows-2025
            sys: windows
            arch: x64
            ext: ".exe"
            friendly_name: "Windows (x64)"
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Cache libclang
        id: cache-libclang
        uses: actions/cache@v4
        with:
          path: lib/libclang
          key: libclang-${{ matrix.os }}-${{ matrix.arch }}-19.1.7

      - name: Download libclang
        if: steps.cache-libclang.outputs.cache-hit != 'true'
        run: |
          pip install -r scripts/requirements.txt
          python scripts/download.py

      - name: Setup Cangjie
        uses: Zxilly/setup-cangjie@v1.4.1
        with:
          channel: "canary"
          token: ${{ secrets.GITCODE_TOKEN }}

      - name: Setup MSYS2
        if: matrix.sys == 'windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
          path-type: inherit

      - name: Build
        if: matrix.sys != 'windows'
        run: |
          python scripts/cjpm.py build --cfg_verbose -V

      - name: Build Windows
        if: matrix.sys == 'windows'
        shell: msys2 {0}
        run: |
          python scripts/cjpm.py build -V

      - name: Test binary
        run: |
          target/release/bin/main${{ matrix.ext }} --version

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cjbind-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            target/release/bin/main*

      - name: Rename binary
        if: github.event_name == 'release'
        shell: bash
        run: |
          cd target/release/bin
          mv main${{ matrix.ext }} cjbind-${{ matrix.sys }}-${{ matrix.arch }}${{ matrix.ext }}

      - name: Upload to Release
        if: github.event_name == 'release'
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ASSET_PATH: target/release/bin/cjbind-${{ matrix.sys }}-${{ matrix.arch }}${{ matrix.ext }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} "$ASSET_PATH#${{ matrix.friendly_name }}" \
            --clobber
